[package]
name = "wei-result"
version = "0.1.1"
edition = "2021"
description = "wei result"
documentation = "https://github.com/zuiyue-com/wei-result"
homepage = "https://github.com/zuiyue-com/wei-result"
license = "MIT OR Apache-2.0"

[dependencies]
serde_json = "1"